spring.application.name=quiz2-doctor-hospital-api

server.port=8080

spring.datasource.url=jdbc:h2:file:./data/quiz2db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=UXVpWjJEb2N0b3JIb3NwaXRhbEFwaVByb2plY3QxMjM0NTY3ODkwU2VjcmV0S2V5
jwt.expiration=3600000
